//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlateApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public string City_Code { get; set; }
        public string City_Name { get; set; }
        public string State_Code { get; set; }
        public string Country_Code { get; set; }
        public string Alias { get; set; }
        public string CrUId { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.DateTime> CrTime { get; set; }
        public bool FrzInd { get; set; }
        public string UpUId { get; set; }
        public Nullable<System.DateTime> UpDate { get; set; }
        public Nullable<System.DateTime> UpTime { get; set; }
        public string UpPlace { get; set; }
        public string TextBlock { get; set; }
        public string PathToText { get; set; }
        public string STD_Code { get; set; }
        public Nullable<int> City_Code_No { get; set; }
        public string TextBlockShort { get; set; }
        public string TextBlockLong { get; set; }
        public string PathToImage { get; set; }
        public string Region_Code { get; set; }
        public string ClientNotes { get; set; }
        public string OpsNotes { get; set; }
        public string SupplierNotes { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string Questions { get; set; }
        public string LongNotes { get; set; }
        public string ShortNotes { get; set; }
        public string OurOpinionNotes { get; set; }
        public string SalesTipNotes { get; set; }
        public string FactSheetNotes { get; set; }
        public string AutoInvoiceRemark { get; set; }
        public int SeqNo { get; set; }
        public string City_Code_Crs { get; set; }
        public Nullable<double> GMapLat { get; set; }
        public Nullable<double> GMapLng { get; set; }
        public Nullable<bool> ShowOnWebInd { get; set; }
        public bool IsHub { get; set; }
        public string RegionCode { get; set; }
        public string DepTaxText { get; set; }
        public string WebPageTitle { get; set; }
        public string WebsiteImagePathName { get; set; }
        public bool IsCapitalCity { get; set; }
        public bool CapitalInd { get; set; }
        public string City_Code_Linked { get; set; }
        public string URLFriendlyName { get; set; }
        public bool IsBoatInd { get; set; }
        public string AccommodationLabelOnWeb { get; set; }
        public string URLFriendlyNameTemp { get; set; }
        public Nullable<bool> UseGroupNameInd { get; set; }
        public Nullable<bool> ImagesSourcedInd { get; set; }
        public string ImagesSourcedBy { get; set; }
        public Nullable<System.DateTime> ImagesSourcedOn { get; set; }
        public string n465x380 { get; set; }
        public Nullable<int> n465x380_ImgCnt { get; set; }
        public string n1460x640 { get; set; }
        public Nullable<int> n1460x640_ImgCnt { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string WebPageLink { get; set; }
        public string n620x380 { get; set; }
        public Nullable<int> n620x380_ImgCnt { get; set; }
        public string GroupName { get; set; }
        public Nullable<short> SerialNo { get; set; }
        public string City_Code_ISO { get; set; }
        public bool IsCapital { get; set; }
        public bool Capital { get; set; }
        public string WebsiteUrl { get; set; }
        public Nullable<int> Serial_No { get; set; }
        public string CityType_Code { get; set; }
        public bool IsBoatCity { get; set; }
        public string C1460x640 { get; set; }
        public string WebShortText { get; set; }
        public string city_name_web { get; set; }
        public string HotelListHeading { get; set; }
        public string ThumbnailImagePath { get; set; }
        public string ThumbnailImageAlt { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public string ImageCode { get; set; }
        public string CMS_ThumbnailImagePath { get; set; }
        public string TourListHeading { get; set; }
        public Nullable<bool> ApplyToAllRegion { get; set; }
        public Nullable<bool> IsFeaturedInd { get; set; }
        public string RegionListHeader { get; set; }
        public Nullable<int> SerialNo_Featured { get; set; }
        public Nullable<bool> ShowOnCountryInd { get; set; }
        public Nullable<bool> ShowOnHotelInd { get; set; }
        public Nullable<short> SerialNoOnCountry { get; set; }
        public Nullable<short> SerialNoOnHotel { get; set; }
        public string NameOnWebCountry { get; set; }
        public string NameOnWebHotel { get; set; }
        public string NameOnWebItinerary { get; set; }
        public string InspirationListHeader { get; set; }
    }
}
