//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlateApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string Country_Code { get; set; }
        public string Country_Name { get; set; }
        public Nullable<short> MinNoOfDays { get; set; }
        public string CrUId { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.DateTime> CrTime { get; set; }
        public bool FrzInd { get; set; }
        public string UpUId { get; set; }
        public Nullable<System.DateTime> UpDate { get; set; }
        public Nullable<System.DateTime> UpTime { get; set; }
        public string UpPlace { get; set; }
        public string ISD_Code { get; set; }
        public string Telex_Code { get; set; }
        public Nullable<short> MinGrpVisaSize { get; set; }
        public Nullable<short> PassValidMonth { get; set; }
        public string Interest_Short_Code { get; set; }
        public string TextBlockLong { get; set; }
        public string TextBlockShort { get; set; }
        public string PathToImage { get; set; }
        public string ManagerUId { get; set; }
        public string LongNotes { get; set; }
        public string ShortNotes { get; set; }
        public string OurOpinionNotes { get; set; }
        public string SalesTipNotes { get; set; }
        public string FactSheetNotes { get; set; }
        public string PassportBeforeTime { get; set; }
        public string AutoInvoiceRemark { get; set; }
        public int SeqNo { get; set; }
        public string VisaNotes { get; set; }
        public string CheckinLetterDocName { get; set; }
        public Nullable<int> CheckinLetterDocRank { get; set; }
        public bool OccupationMandatoryForVisa { get; set; }
        public string TimeDiffToGMT { get; set; }
        public string ISOCode { get; set; }
        public string WebsitePageCode { get; set; }
        public Nullable<bool> ShowOnWebInd { get; set; }
        public string Interest_Short_Code_Web { get; set; }
        public string DepTaxText { get; set; }
        public string WebPageTitle { get; set; }
        public string UseRegionOrCityInFIT { get; set; }
        public bool OnSaleInd { get; set; }
        public string CheckInLetterDocName_2010 { get; set; }
        public string WebPageTitle_Tours { get; set; }
        public string WebsiteImagePathName { get; set; }
        public string ISOName { get; set; }
        public string TeamName { get; set; }
        public Nullable<bool> EUInd { get; set; }
        public string SellingType { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string City_Code_Capital { get; set; }
        public string country_name_web { get; set; }
        public string country_name_menu { get; set; }
        public string DetailPDFPathName { get; set; }
        public Nullable<bool> ShowHolidayIdeas1 { get; set; }
        public Nullable<bool> ShowHolidayIdeas2 { get; set; }
        public Nullable<bool> ShowHolidayIdeas3 { get; set; }
        public Nullable<bool> WebsiteToHotelInd { get; set; }
        public string URLFriendlyName { get; set; }
        public string URLFriendlyNameForCountryHolidays { get; set; }
        public Nullable<bool> ShowOnOnlineAddress { get; set; }
        public Nullable<bool> UseAllBoatTemplate { get; set; }
        public Nullable<bool> ShowMapInd { get; set; }
        public Nullable<bool> ShowOnWebGrpEnquiryInd { get; set; }
        public Nullable<int> SerialNoOnlineAddress { get; set; }
        public string ISO3Code { get; set; }
        public Nullable<bool> ImagesSourcedInd { get; set; }
        public string ImagesSourcedBy { get; set; }
        public Nullable<System.DateTime> ImagesSourcedOn { get; set; }
        public string n465x380 { get; set; }
        public Nullable<int> n465x380_ImgCnt { get; set; }
        public string n1460x640 { get; set; }
        public Nullable<int> n1460x640_ImgCnt { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string WebPageLink { get; set; }
        public Nullable<bool> UseGroupNameInd { get; set; }
        public Nullable<bool> ShowCountryInfoTabsInd { get; set; }
        public string WebPageTitle_Interest { get; set; }
        public string CountryNameForImgPath { get; set; }
        public string Country_Code_Domicile { get; set; }
        public string WebShortText { get; set; }
        public string ThumbnailImagePath { get; set; }
        public string ThumbnailImageAlt { get; set; }
        public Nullable<bool> AllowExpert { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public Nullable<bool> IsDirectToHotelInd { get; set; }
        public string AmazonURL { get; set; }
        public string WebsiteURL { get; set; }
        public string ImageCode { get; set; }
        public string CMS_ThumbnailImagePath { get; set; }
        public string TourListHeading { get; set; }
        public string CountryExpListHeading { get; set; }
        public Nullable<bool> ApplyToAllRegion { get; set; }
        public Nullable<bool> IsForthComingInd { get; set; }
        public string ExcursionListHeading { get; set; }
        public string HotelListHeading { get; set; }
        public string OfferListHeading { get; set; }
        public string WebPageTitle_Gallery { get; set; }
        public string MetaDescription_Gallery { get; set; }
        public string Metakeyword_Gallery { get; set; }
        public string InspirationListHeader { get; set; }
        public Nullable<bool> IsFeaturedInd { get; set; }
        public Nullable<int> SerialNo_Featured { get; set; }
        public string CityListHeader { get; set; }
        public Nullable<double> GMapLat { get; set; }
        public Nullable<double> GMapLng { get; set; }
    }
}
