//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlateApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Hotel_Code { get; set; }
        public string Hotel_Name { get; set; }
        public string ShortName { get; set; }
        public string City_Code { get; set; }
        public string Notes { get; set; }
        public string TextBlockLong { get; set; }
        public string PathToTextLong { get; set; }
        public string CrUId { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.DateTime> CrTime { get; set; }
        public bool FrzInd { get; set; }
        public string UpUId { get; set; }
        public Nullable<System.DateTime> UpDate { get; set; }
        public Nullable<System.DateTime> UpTime { get; set; }
        public string UpPlace { get; set; }
        public Nullable<short> SerialNo { get; set; }
        public string BClass_Code { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public bool AgentInd { get; set; }
        public string GroupName { get; set; }
        public string Keyword { get; set; }
        public string HostRating { get; set; }
        public string HotelRating { get; set; }
        public string HostPref { get; set; }
        public string TextBlockShort { get; set; }
        public string PathToTextShort { get; set; }
        public string PathToImage { get; set; }
        public string ClientNotes { get; set; }
        public string OpsNotes { get; set; }
        public string SupplierNotes { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string Questions { get; set; }
        public string LongNotes { get; set; }
        public string ShortNotes { get; set; }
        public string OurOpinionNotes { get; set; }
        public string SalesTipNotes { get; set; }
        public string FactSheetNotes { get; set; }
        public Nullable<System.DateTime> LastVisitedDate { get; set; }
        public Nullable<double> GMapLat { get; set; }
        public Nullable<double> GMapLng { get; set; }
        public Nullable<bool> ShowOnWebInd { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public string NotesSeason { get; set; }
        public string WebPageTitle { get; set; }
        public Nullable<bool> IsBoatInd { get; set; }
        public string MealBasis_Code_Short { get; set; }
        public Nullable<bool> IsFeaturedInd { get; set; }
        public string HotelFormatInItinerary { get; set; }
        public string URLFriendlyName { get; set; }
        public Nullable<int> Hotel_Code_Link { get; set; }
        public string URLFriendlyNameTemp { get; set; }
        public Nullable<bool> UseForDummyItinerary { get; set; }
        public string WebOfferMemo { get; set; }
        public Nullable<bool> ShowOfferOnWebInd { get; set; }
        public Nullable<System.DateTime> ShowOfferOnDate { get; set; }
        public Nullable<System.DateTime> ShowOfferToDate { get; set; }
        public string WebOfferShortText { get; set; }
        public int HotelCode { get; set; }
        public Nullable<int> SerialNo_City { get; set; }
        public string hotel_name_web { get; set; }
        public string ThumbnailImagePath { get; set; }
        public string ThumbnailImageAlt { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string WebsiteURL { get; set; }
        public string AccommodationType { get; set; }
        public Nullable<bool> IsRailInd { get; set; }
        public string AccommodationCategoryWeb { get; set; }
        public Nullable<int> SerialNo_Country { get; set; }
        public string Country_Code { get; set; }
        public string State_Code { get; set; }
        public string WebShortText { get; set; }
        public string CMS_ThumbnailImagePath { get; set; }
        public string IntroText { get; set; }
        public string MetaDescription { get; set; }
        public string ImageCode { get; set; }
        public string TagName { get; set; }
        public string MetaKeyword { get; set; }
        public string GuidelinePriceNotes { get; set; }
        public Nullable<int> SerialNo_Featured { get; set; }
    }
}
